version: "2"
services:
  mongo:
    image: mongo:3.0.4
    volumes:
      - /data/db
    ports:
      - "27017:27017"
    command: --smallfiles --rest --noauth
  api:
    build:
      context: .
      dockerfile: "Dockerfile.test"
    volumes:
      - .:/app
    ports:
      - "41960:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=mongodb://mongo
      - DB_PORT=27017
    depends_on:
      - mongo